#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define VIEW_RANGE 10
#define VIEW_BOX_LENGTH 21 //2*VIEW_RANGE + 1
#define VIEW_BOX_PERIMETER 40 //4*VIEW_RANGE
#define VIEW_RANGE_DEFAULT 7

//#define GOD_VISION

#define MOVE_MODE_SIMPLE 0
#define MOVE_MODE_DIRECTIONAL 1
#define moveMode MOVE_MODE_SIMPLE

#endif
